In [1]:
#Dependencies
import pandas as pd

In [2]:
path = "open-beer-database-breweries.csv"
csv_breweries = pd.read_csv(path, sep=";")
print(csv_breweries)

        id                                   breweries  \
0        9                            Aberdeen Brewing
1       10                       Abita Brewing Company
2       19                                     Aldaris
3       21                            AleSmith Brewing
4       31                       Alvinne Picobrouwerij
5       48                Arcobrau Grafliches Brauhaus
6       51             Asheville Pizza and Brewing Co.
7       75           Barley Brothers Brewery and Grill
8       80                         Barley's Brewing #1
9       83                    Barrel House Brewing Co.
10      96                Beermann's Beerwerks BrewPub
11     109                       Bierbrouwerij Bavaria
12     117                            Big Hole Brewing
13     122                             Big Sky Brewing
14     133                 BJ's Restaurant and Brewery
15     139                      Blitz-Weinhard Brewing
16     148                        Boddington's Brewery
17     150                      Bonaventure Brewing Co
18     176                       Brasserie de la Senne
19     178                     Brasserie De Silenrieux
20     197                          Brasserie Lefebvre
21     206                               Brauerei Beck
22     207         Brauerei C. & A. Veltins GmbH & Co.
23     211                                Brauerei Gss
24     213                               Brauerei Hrle
25     233                            Brauhaus Sternen
26     235                   Breckenridge BBQ of Omaha
27     248                            Brewery De Troch
28     294                      Brouwerij Slaghmuylder
29     298                           Brouwerij Strubbe
...    ...                                         ...
1392  1263                         Thunderhead Brewery
1393  1265        Tied House Cafe & Brewery - San Jose
1394  1281                      Traquair House Brewery
1395  1282                     Trinity Brewing Company
1396  1284                 Triumph Brewing of New Hope
1397  1286                              Troegs Brewing
1398  1287  Tropical Beverage (International) Co., Ltd
1399  1305                               Ukiah Brewing
1400  1347                      Weissbierbrauerei Hopf
1401  1361                     Widmer Brothers Brewing
1402  1366                     William Kuether Brewing
1403  1385                    Youngs & Company Brewery
1404  1402                     Warwick Valley Wine Co.
1405  1403                          The Nook Brewhouse
1406  1405                           Baltika Breweries
1407  1401                  Half Pints Brewing Company
1408  1407              Catawba Valley Brewing Company
1409  1232                               Tailgate Beer
1410  1246                                  The Bruery
1411  1285                Triumph Brewing of Princeton
1412  1299                   Two Dogs Beverage Company
1413  1311                        Unionsbru Haidhausen
1414  1330                      Voodoo Brewing Co.,LLC
1415  1363                     Wild Goose Brewery, LLC
1416  1369                          Wilmington Brewing
1417  1378                          Wye Valley Brewery
1418  1381                            Yaletown Brewing
1419  1386                  Zea Rotisserie and Brewery
1420  1406                           Baltika Breweries
1421  1414                Black Creek Historic Brewery

                            address1                  address2  \
0                   210 Aberdeen Dr.                       NaN
1                        PO Box 1510                       NaN
2                     Tvaika iela 44                       NaN
3                   9368 Cabot Drive                       NaN
4             Oostrozebekestraat 114                       NaN
5                      Schlossalle 1                       NaN
6                675 Merrimon Avenue                       NaN
7           1425 McCulloch Boulevard                       NaN
8              467 North High Street                       NaN
9                544B W. Liberty St.                       NaN
10                               NaN                       NaN
11     Burg. van den Heuvelstraat 35                       NaN
12              401 East Main Street                       NaN
13                5417 Trumpeter Way                       NaN
14                     600 Brea Mall                       NaN
15                 Portland OR 97209                       NaN
16                               NaN                       NaN
17    404 South Figueroa Street #418                       NaN
18        Victor Nonnemansstraat 40a                       NaN
19                  Rue de Noupr s/n                       NaN
20                Chemin du Croly 52                       NaN
21                    Am Deich 18-19                       NaN
22                     An der Streue                       NaN
23                   Brauhausgasse 1                       NaN
24                 Am Hopfengarten 5                       NaN
25                Hohenzornstrasse 2                       NaN
26                               NaN                       NaN
27                    Langestraat 20                       NaN
28                Denterhoutembaan 2                       NaN
29                           Markt 1                       NaN
...                              ...                       ...
1392             18 East 21st Street                       NaN
1393              65 North San Pedro                       NaN
1394           Innerleithen EH44 6PW                       NaN
1395         1446 Garden of the Gods                       NaN
1396                400 Union Square                       NaN
1397               800 Paxton Street                       NaN
1398     35 Soi Prommit, Sukumvit 39                       NaN
1399          102 South State Street                       NaN
1400               Schtzenstrae 8-10                       NaN
1401        929 North Russell Street                       NaN
1402                             NaN                       NaN
1403                  26 Osiers Road                Wandsworth
1404              114 Little York Rd                       NaN
1405                             NaN                       NaN
1406            6 Verkhny per., d. 3                       NaN
1407            550 Roseberry Street                       NaN
1408                   P.O. Box 1154                       NaN
1409               6648 Reservoir Ln                       NaN
1410                    715 Dunn Way                       NaN
1411               138 Nassau Street                       NaN
1412               272 Plandome Road                       NaN
1413                Einsteinstrae 42                       NaN
1414                215 1/5 Arch St.                       NaN
1415            4607 Wedgewood Blvd.                       NaN
1416                             NaN                       NaN
1417              Stoke Lacy HR7 4HG                       NaN
1418            1111 Mainland Street                       NaN
1419         1525 St. Charles Avenue                       NaN
1420            6 Verkhny per., d. 3                       NaN
1421     Black Creek Pioneer Village  1000 Murray Ross Parkway

                        city                   state      code  \
0                 Valparaiso                 Indiana       NaN
1              Abita Springs               Louisiana     70420
2                        Rga                     NaN       NaN
3                  San Diego              California     92126
4               Ingelmunster         West-Vlaanderen       NaN
5                       Moos       Baden-Wurttemberg     94554
6                  Asheville          North Carolina     28804
7           Lake Havasu City                 Arizona     86403
8                   Columbus                    Ohio     43215
9                 Cincinnati                    Ohio     45214
10                   Lincoln              California       NaN
11                  Lieshout                     NaN         0
12                  Belgrade                 Montana     59714
13                  Missoula                 Montana     59808
14                      Brea              California       NaN
15                  Portland                  Oregon       NaN
16                Manchester              Manchester       NaN
17               Los Angeles              California     90071
18        Sint-Pieters-Leeuw          Vlaams Brabant       NaN
19    Cerfontaine-Silenrieux                   Namur       NaN
20                   Quenast          Brabant Wallon       NaN
21                    Bremen                  Bremen       NaN
22                  Meschede     Nordrhein-Westfalen       NaN
23                Leoben-Gss                     NaN       NaN
24      Leutkirch im AllgÃ¤u      Baden-WÃ¼rttemberg       NaN
25                Frauenfeld                     NaN       NaN
26                     Omaha                Nebraska       NaN
27                    Ternat          Vlaams Brabant       NaN
28                    Ninove         Oost-Vlaanderen       NaN
29                  Ichtegem         West-Vlaanderen       NaN
...                      ...                     ...       ...
1392                 Kearney                Nebraska     68847
1393                San Jose              California     95110
1394            Innerleithen                Scotland       NaN
1395        Colorado Springs                Colorado     80907
1396                New Hope            Pennsylvania     18938
1397              Harrisburg            Pennsylvania     17104
1398                 Bangkok                     NaN       NaN
1399                   Ukiah              California     95482
1400                Miesbach                  Bayern       NaN
1401                Portland                  Oregon     97227
1402              Clear Lake               Wisconsin       NaN
1403                  London                     NaN  SW18 1NH
1404                 Warwick                      NY     10990
1405                     NaN                     NaN       NaN
1406          St. Petersburg                     NaN    194292
1407                Winnipeg                Manitoba       NaN
1408             Glen Alpine                      NC     28628
1409               San Diego              California     92155
1410               Placentia              California     92870
1411               Princeton              New Jersey      8542
1412               Manhasset                New York     11030
1413                  Mnchen                  Bayern       NaN
1414               Meadville            Pennsylvania     16335
1415                Fredrick                Maryland     21703
1416              Wilmington          North Carolina       NaN
1417              Stoke Lacy  Hereford and Worcester       NaN
1418               Vancouver        British Columbia         0
1419             New Orleans               Louisiana     70130
1420          St. Petersburg                     NaN    194292
1421                 Toronto                 Ontario   M3J 2P3

             country                 phone  \
0      United States        (219) 548-3300
1      United States          800-737-2311
2             Latvia         371-70-23-200
3      United States        1-858-549-9888
4            Belgium     32-051-/-30-55-17
5            Germany       09938 / 918 180
6      United States        (828) 254-1281
7      United States        1-928-505-7837
8      United States        1-614-228-2537
9      United States          513-421-2337
10     United States                   NaN
11       Netherlands        31-0499-428111
12     United States        1-800-793-6656
13     United States        1-800-559-2774
14     United States          714-990-2095
15     United States                   NaN
16    United Kingdom                   NaN
17     United States        (213) 236-0802
18           Belgium    32-0497-/-93.23.75
19           Belgium       32-071-63-32-01
20           Belgium       32-067-67-07-66
21           Germany     49-(0)421-/-50940
22           Germany    49-(0)2934-/-959-0
23           Austria  43-0-38-42/20-90-58-
24           Germany   49-(0)7561-/-9828-0
25       Switzerland      41-052-728-99-09
26     United States                   NaN
27           Belgium       32-02-582-10-27
28           Belgium       32-054-33-18-31
29           Belgium       32-051-58-81-16
...              ...                   ...
1392   United States        1-308-237-1558
1393   United States        1-408-295-2739
1394  United Kingdom     44-(01896)-830323
1395   United States          719-634-0029
1396   United States        1-215-862-8300
1397   United States        1-717-232-1297
1398        Thailand                   NaN
1399   United States        1-707-468-5898
1400         Germany   49-(0)8025-/-2959-0
1401   United States        1-503-281-2437
1402   United States                   NaN
1403         England         020 8875 7000
1404   United States        (845) 258-4858
1405  United Kingdom                   NaN
1406          Russia        (812)325-93-25
1407          Canada                   NaN
1408   United States          828-430-6883
1409   United States          619.466.2337
1410   United States          714-996-6258
1411   United States        1-609-924-7855
1412   United States        1-516-869-6568
1413         Germany     49-(0)89-/-477677
1414   United States      1-(412)-468-0295
1415   United States        (301) 694-7899
1416   United States                   NaN
1417  United Kingdom     44-(01885)-490505
1418          Canada        1-604-688-0039
1419   United States                   NaN
1420          Russia        (812)325-93-25
1421          Canada          416 736-1733

                                          website                 filepath  \
0                                             NaN                      NaN
1                           http://www.abita.com/                      NaN
2                                             NaN                      NaN
3                            http://alesmith.com/                      NaN
4                                             NaN                      NaN
5                         http://www.arcobraeu.de                      NaN
6                  http://www.ashevillepizza.com/                      NaN
7                                             NaN                      NaN
8                                             NaN                      NaN
9                      http://www.barrelhouse.com                      NaN
10                                            NaN                      NaN
11                                            NaN                      NaN
12                                            NaN                      NaN
13                                            NaN                      NaN
14        http://www.bjsrestaurants.com/beer.aspx                      NaN
15                                            NaN                      NaN
16                                            NaN                      NaN
17             http://www.bonaventurebrewing.com/                      NaN
18                                            NaN                      NaN
19                                            NaN                      NaN
20                                            NaN                      NaN
21                                            NaN                      NaN
22                                            NaN                      NaN
23                                            NaN                      NaN
24                                            NaN                      NaN
25                                            NaN                      NaN
26                                            NaN                      NaN
27                                            NaN                      NaN
28                                            NaN                      NaN
29                                            NaN                      NaN
...                                           ...                      ...
1392                                          NaN                      NaN
1393                                          NaN                      NaN
1394                                          NaN                      NaN
1395                      http://trinitybrew.com/                      NaN
1396               http://www.triumphbrewing.com/                      NaN
1397                       http://www.troegs.com/                      NaN
1398                    http://www.tropbevco.com/                      NaN
1399                                          NaN                      NaN
1400                                          NaN                      NaN
1401                                          NaN                      NaN
1402                                          NaN                      NaN
1403                      http://www.youngs.co.uk                      NaN
1404                      http://www.wvwinery.com                      NaN
1405                                          NaN                      NaN
1406                      http://baltikabeer.com/         baltika_logo.gif
1407              http://www.halfpintsbrewing.com                      NaN
1408  http://www.catawbavalleybrewingcompany.com/  catawba-valley-logo.jpg
1409    http://www.tailgatebeer.com/indexmain.php                      NaN
1410                    http://www.thebruery.com/                      NaN
1411                                          NaN                      NaN
1412                                          NaN                      NaN
1413                                          NaN                      NaN
1414                http://www.voodoobrewery.com/                      NaN
1415             http://www.wildgoosebrewery.com/                      NaN
1416                                          NaN                      NaN
1417                                          NaN                      NaN
1418                                          NaN                      NaN
1419                http://www.zearestaurants.com                      NaN
1420                      http://baltikabeer.com/        baltika_logo1.gif
1421             http://www.blackcreekbrewery.ca/            bchb_logo.png

                                               descript  \
0                                                   NaN
1     Founded in 1986, the Abita Brewing Company is ...
2                                                   NaN
3                                                   NaN
4                                                   NaN
5                                                   NaN
6     Asheville Brewpub, Brewery, Movie Theater and ...
7                                                   NaN
8                                                   NaN
9     Established as a brewpub in 1995 in the histor...
10                                                  NaN
11                                                  NaN
12                                                  NaN
13                                                  NaN
14                                                  NaN
15                                                  NaN
16                                                  NaN
17    Local beers brewed on-site on the 4th floor pa...
18                                                  NaN
19                                                  NaN
20                                                  NaN
21                                                  NaN
22                                                  NaN
23                                                  NaN

In [40]:
breweries_df = pd.DataFrame(csv_breweries)
breweries_df.head()

,id,breweries,address1,address2,city,state,code,country,phone,website,filepath,descript,last_mod,coordinates
0,9,Aberdeen Brewing,210 Aberdeen Dr.,NaN,Valparaiso,Indiana,NaN,United States,(219) 548-3300,NaN,NaN,NaN,2010-07-22T16:00:20-04:00,"41.4392, -87.1078"
1,10,Abita Brewing Company,PO Box 1510,NaN,Abita Springs,Louisiana,70420,United States,800-737-2311,http://www.abita.com/,NaN,"Founded in 1986, the Abita Brewing Company is ...",2010-07-22T16:00:20-04:00,"30.5049, -89.944"
2,19,Aldaris,Tvaika iela 44,NaN,Rga,NaN,NaN,Latvia,371-70-23-200,NaN,NaN,NaN,2010-07-22T16:00:20-04:00,NaN
3,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144"
4,31,Alvinne Picobrouwerij,Oostrozebekestraat 114,NaN,Ingelmunster,West-Vlaanderen,NaN,Belgium,32-051-/-30-55-17,NaN,NaN,NaN,2010-07-22T16:00:20-04:00,"50.919, 3.2632"

In [68]:
breweries_df = breweries_df.rename(columns={"id": "brewery_id","state":"STATE"})
breweries_df.head()

,brewery_id,breweries,address1,address2,city,STATE,code,country,phone,website,filepath,descript,last_mod,coordinates
0,9,Aberdeen Brewing,210 Aberdeen Dr.,NaN,Valparaiso,Indiana,NaN,United States,(219) 548-3300,NaN,NaN,NaN,2010-07-22T16:00:20-04:00,"41.4392, -87.1078"
1,10,Abita Brewing Company,PO Box 1510,NaN,Abita Springs,Louisiana,70420,United States,800-737-2311,http://www.abita.com/,NaN,"Founded in 1986, the Abita Brewing Company is ...",2010-07-22T16:00:20-04:00,"30.5049, -89.944"
2,19,Aldaris,Tvaika iela 44,NaN,Rga,NaN,NaN,Latvia,371-70-23-200,NaN,NaN,NaN,2010-07-22T16:00:20-04:00,NaN
3,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144"
4,31,Alvinne Picobrouwerij,Oostrozebekestraat 114,NaN,Ingelmunster,West-Vlaanderen,NaN,Belgium,32-051-/-30-55-17,NaN,NaN,NaN,2010-07-22T16:00:20-04:00,"50.919, 3.2632"

In [70]:
#Google search says id 812 should be "magic hat brewery" for beer 'hocus pocus'
check = breweries_df[breweries_df["brewery_id"]==812]['breweries']
print(check)

763    Magic Hat
Name: breweries, dtype: object

In [71]:
path = "beers-fork.csv"
csv_beers = pd.read_csv(path, sep=",")
print(csv_beers)

       id   abv                             name  brewery_id
0       1   4.5                      Hocus Pocus         812
1       2   6.7                Grimbergen Blonde         264
2       3   9.1           Widdershins Barleywine         779
3       4   8.5                          Lucifer         287
4       5   4.0                           Bitter        1056
5       6   5.2                    Winter Warmer        1385
6       7   6.0         Winter Welcome 2007-2008        1099
7       8   5.0                    Oatmeal Stout        1099
8       9   0.0                  Espresso Porter         501
9      10   0.0                  Chocolate Stout         545
10     11   7.0  Hitachino Nest Real Ginger Brew         742
11     12   4.0                      JuJu Ginger         779
12     13   0.0                   The Kidd Lager         545
13     14   7.0                   Imperial Stout        1099
14     15   9.0          Oak-Aged Belgian Tripel        1315
15     16   8.0                      Ultrablonde         168
16     17   6.2               Wiesen Edel Weisse        1023
17     18  10.0                 Old Foghorn 2001          39
18     19   6.0                        Framboise         196
19     20   8.7       Cow Palace Scotch Ale 1998         483
20     21   9.6                     Bigfoot 2001        1142
21     22   9.6                     Bigfoot 2002        1142
22     23   9.6                     Bigfoot 2003        1142
23     24   9.6                     Bigfoot 2004        1142
24     25   9.6                     Bigfoot 2005        1142
25     26   5.9                       Winter Ale        1220
26     27   5.6             Full Moon Winter Ale         878
27     28   7.0                        Odell IPA         935
28     29   0.0               Ornery Amber Lager        1271
29     30   4.8                 Cutthroat Porter         935
..    ...   ...                              ...         ...
970   971   6.6                      Helles Bock        1158
971   972   5.3               Burns Scottish Ale        1158
972   973   7.2          Anniversary IPA Ahtanum        1158
973   974   7.2          Anniversary IPA Glacier        1158
974   975   7.2                    Route 113 IPA        1158
975   976   4.1              Featherweight Lager        1158
976   977   5.7                     Royal Weisse        1158
977   978   5.5                 Phoenix Pale Ale        1158
978   979   4.7              Helles Golden Lager        1158
979   980   4.2                  Golden Treasure         409
980   981   6.0     Crabby Larry's Irish Red Ale         409
981   982   5.4            Calico Jack Amber Ale         409
982   983   0.0                         Pale Ale         409
983   984   0.0                     Summer Lager         409
984   985   0.0                      Irish Stout        1011
985   986   0.0                       Hop Hazard        1011
986   987   0.0                   Indian Red Ale        1011
987   988   0.0                            Lager        1011
988   989   0.0                      Special Ale        1011
989   990   0.0                    Irish Red Ale         841
990   991   8.0                          Abbey 8         841
991   992   6.2                 Farmhouse Saison         841
992   993   6.6                    East Kent IPA         841
993   994   6.5       French Country Spring Beer         841
994   995   5.7                  Black Lab Stout         841
995   996   5.5               Old Rogue Pale Ale         841
996   997   4.0                Unicorn Amber Ale         841
997   998   3.5                      Light Lager         841
998   999   0.0                  Half Again Bock         721
999  1000   0.0                 Winterfest Lager         721

[1000 rows x 4 columns]

In [72]:
beers_df = pd.DataFrame(csv_beers)
beers_df.head()

   id  abv                    name  brewery_id
0   1  4.5             Hocus Pocus         812
1   2  6.7       Grimbergen Blonde         264
2   3  9.1  Widdershins Barleywine         779
3   4  8.5                 Lucifer         287
4   5  4.0                  Bitter        1056

In [73]:
booze_df = pd.merge(breweries_df,beers_df,on="brewery_id")
booze_df.head()

,brewery_id,breweries,address1,address2,city,STATE,code,country,phone,website,filepath,descript,last_mod,coordinates,id,abv,name
0,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",384,10.0,Grand Cru 2006
1,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",811,9.5,Wee Heavy
2,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",901,5.0,X Extra Pale Ale
3,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",923,12.0,Speedway Stout
4,31,Alvinne Picobrouwerij,Oostrozebekestraat 114,NaN,Ingelmunster,West-Vlaanderen,NaN,Belgium,32-051-/-30-55-17,NaN,NaN,NaN,2010-07-22T16:00:20-04:00,"50.919, 3.2632",167,10.5,Podge Belgian Imperial Stout

In [74]:
USA_booze_df = booze_df.loc[booze_df['country']=='United States']
USA_booze_df.head()

,brewery_id,breweries,address1,address2,city,STATE,code,country,phone,website,filepath,descript,last_mod,coordinates,id,abv,name
0,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",384,10.0,Grand Cru 2006
1,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",811,9.5,Wee Heavy
2,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",901,5.0,X Extra Pale Ale
3,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",923,12.0,Speedway Stout
6,122,Big Sky Brewing,5417 Trumpeter Way,NaN,Missoula,Montana,59808,United States,1-800-559-2774,NaN,NaN,NaN,2010-07-22T16:00:20-04:00,"46.9223, -114.073",172,0.0,Crystal Ale

In [76]:
us_state_abbrev = {
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arizona': 'AZ',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
}
USA_booze_df['state'] = USA_booze_df['STATE'].map(us_state_abbrev)
USA_booze_df.head()

C:\Users\Josh\Anaconda3\lib\site-packages\ipykernel_launcher.py:53: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,brewery_id,breweries,address1,address2,city,STATE,code,country,phone,website,filepath,descript,last_mod,coordinates,id,abv,name,state
0,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",384,10.0,Grand Cru 2006,CA
1,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",811,9.5,Wee Heavy,CA
2,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",901,5.0,X Extra Pale Ale,CA
3,21,AleSmith Brewing,9368 Cabot Drive,NaN,San Diego,California,92126,United States,1-858-549-9888,http://alesmith.com/,NaN,NaN,2010-07-22T16:00:20-04:00,"32.892, -117.144",923,12.0,Speedway Stout,CA
6,122,Big Sky Brewing,5417 Trumpeter Way,NaN,Missoula,Montana,59808,United States,1-800-559-2774,NaN,NaN,NaN,2010-07-22T16:00:20-04:00,"46.9223, -114.073",172,0.0,Crystal Ale,MT

In [77]:
USA_booze_df.to_csv("drunk_python.csv", header = True)